### ISSUE TITLE
Image tag issue

### ISSUE THREAD

**Issue by jimbo64** [jimbo64/wf#2]
On the right hand side of my blog page, I have a recent posts list. For some reason, it's pulling the image tags. This only appears when a link to an article is clicked. 

![imgtag](https://cloud.githubusercontent.com/assets/19889143/16099753/f4b078de-3351-11e6-89db-7129e9fe58b9.png)

**Comment by keerin** [comment]
I think we can use a regular expression to remove the MarkDown image tag. I'll try to write this tonight or tomorrow. I'm not sure if Liquid will accept regex however. Will have to try and see.

**Comment by keerin** [comment]
The following regex will remove the MarkDown for inserting <img> tags:

`!\[.*?\]\(.*?\)`

**Comment by keerin** [comment]
Argh no regex support in Liquid! I think this can instead be done with a really simply JS script instead. reckon you can do this? I have very little JS experience. What we need is - when loading blog posts, run the regex above in the sidebar.

**Comment by keerin** [comment]
This should work, but I have no idea how to select the read more in the sidebar

`var Stripped = String.replace(!\[.*?\]\(.*?\),"");`

**Comment by jimbo64** [comment]
your mum
